appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars: 
  - name: ENV_VAR_ONE
    value: "valueone"
  - name: ENV_VAR_TWO
    value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP

readinessProbe:
  httpGet:
    path: "/_healthz"
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: "/_healthz"
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
