appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.10.1
containerPort: 9555
containerEnvVars: 
- name: PORT
  value: "9555"

servicePort: 9555
serviceType: ClusterIP 

readinessProbe:
  grpc:
    port: 9555
  initialDelaySeconds: 20
  periodSeconds: 15

livenessProbe:
  grpc:
    port: 9555
  initialDelaySeconds: 20
  periodSeconds: 15

resources:
  requests:
    cpu: "200m"
    memory: "180Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"