appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.10.1
containerPort: 7070
containerEnvVars: 
- name: PORT
  value: "7070"
- name: REDIS_ADDR
  value: "redis-cart:6379"

servicePort: 7070
serviceType: ClusterIP

readinessProbe:
  grpc:
    port: 7070
  initialDelaySeconds: 15

livenessProbe:
  grpc:
    port: 7070
  periodSeconds: 10

resources:
  requests:
    cpu: "200m"
    memory: "64Mi"
  limits:
    cpu: "300m"
    memory: "128Mi"