appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.10.1
containerPort: 7000
containerEnvVars: 
- name: PORT
  value: "7000"

servicePort: 7000
serviceType: ClusterIP

readinessProbe:
  grpc:
    port: 7000
  periodSeconds: 5

livenessProbe:
  grpc:
    port: 7000
  periodSeconds: 5

