appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.10.1
containerPort: 3550
containerEnvVars: 
- name: PORT
  value: "3550"

servicePort: 3550
serviceType: ClusterIP

readinessProbe:
  grpc:
    port: 3550

livenessProbe:
  grpc:
    port: 3550

